version: '2'
networks:
  samllogin:
    driver: bridge
services:
   samlsp:
     image: kvalitetsit/kitcaddy:1.2.3
     volumes:
       - ./echo/certificates/echo.cert:/sp/sp.cer
       - ./echo/certificates/echo.pem:/sp/sp.pem
       - ./echo/config.json:/config/config.json
       - ./echo/config.json:/config/config-email.json
     command: -config /config/config.json # change config.json to config-email.json to use email realm that fetch the email for a user on login
     ports:
      - "80:8585"
     networks:
      - samllogin
   mongo:
     image: mongo:3.6
     networks:
      - samllogin
   echo:
     image: mendhak/http-https-echo
     networks:
      - samllogin
